name: Instagram Guncelleme

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # İzinleri koda da ekliyoruz
      contents: write
    steps:
      - uses: actions/checkout@v4 # Versiyonu yükselttik

      - name: Python Kur
        uses: actions/setup-python@v5 # Versiyonu yükselttik
        with:
          python-version: '3.10'

      - name: Instaloader Yukle ve Resimleri Cek
        run: |
          pip install instaloader
          # Profil adini buraya yazin
          instaloader --no-videos --no-metadata-json --no-captions --no-compress-json --count 9 HEDEF_PROFIL_ADI
          
      - name: Degisiklikleri Kaydet ve Yukle
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Instagram Akışı Güncellendi" || echo "Degisiklik yok"
          git push
